[build]
  functions = "functions"
  command = "#"
[template.environment]
  PAYMONGO_EMAIL = "Type Username"
  PAYMONGO_PASS = "Type Password"
  PAYMONGO_LIVE_MODE = "Set True If Paymongo is Live"
  PAYMONGO_MERCHANT_NAME = "Your Paymongo Merchant Name"
  REFUND_POLICY_HRS = "Refund Policy No Of Hours, i.e.: 48"
  GOOGLE_SERVICE_ACCOUNT_EMAIL = "Google Service Account Email"
  GOOGLE_SPREADSHEET_ID_FROM_URL = "Google Spreadsheet ID"
  GOOGLE_PRIVATE_KEY = "Goggle Account Private Key"
  SES_ACCESS_KEY = "Amazon SES Access Key"
  SES_SECRET_KEY = "Amazon SES Secret Key"
  SES_REGION = "Amazon SES Region"
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
